spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to Bank accounts related QA APIs "
  contactDetails:
    name: "Mike J - QA - Lead"
    email: "mike@gmail.com"
  onCallSupport:
    - (049) 000-1234
    - (049) 000-1345